### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by rbalint** [jlehtine/c-pluff#10]
Please make a new release containing #8.

Kodi keeps embedding and rebuilding C-Pluff because there is no official c-pluff release that it could use.

(I'm the Debian Kodi & C-Pluff maintainer)

**Comment by jlehtine** [comment]
Hi! Thank you for your effort and for the reminder :) I have just made a new C-Pluff release 0.2.0 containing the current master branch. Please let me know if you find any issues with it. The test suite passed alright.

**Comment by rbalint** [comment]
Thanks. I've uploaded 0.2.0 to Debian.

I'm removing myself from the Uploader role of the package because I was interested packaging it for Kodi and in the meantime Kodi stopped using C-pluff (https://github.com/xbmc/xbmc/pull/14908). Feel free to continue maintaining the package, you are listed as the maintainer. If you don't want to maintain the package I can file to bug for removing or for orphaning it.
https://www.debian.org/devel/wnpp/
